mmi_bootstrap:
    resource: "@MmiBootstrapBundle/Controller/"
    type:     annotation
    prefix:   /bootstrap

mmi_hello:
    resource: "@MmiHelloBundle/Controller/"
    type:     annotation
    prefix:   /hello